### PR TITLE
Escape HTML in cells by using underscores escaper, fixes #1738

### LINKED ISSUE #1738: [WebUI] js executed in history-page
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.2

### Description (Please provide a descriptive summary of the issue):
It seams that that the webui does not handle subjects correctly and executes javascript.
Maybe other columns are affected also.
### Steps to reproduce:
Send mail with 
`<script>alert('XSS');</script>`
in subject.
### Expected results:
Show subject
### Actual results:
Alertbox pops up, no subjects shown

### PR DESCRIPTION
**Pull request by andryyy**

### CODE REVIEW

File: interface/js/app/history.js [hunk 1]
```diff
@@ -26,7 +26,22 @@ define(['jquery', 'footable', 'humanize'],
...
     var ft = {};
-
+    var htmlEscapes = {
+      '&': '&amp;',
+      '<': '&lt;',
+      '>': '&gt;',
+      '"': '&quot;',
+      "'": '&#x27;',
+      '/': '&#x2F;'
+    };
```
Comment (vstakhov) [inline interface/js/app/history.js]:
```javascript
var entityMap = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
  '/': '&#x2F;',
  '`': '&#x60;',
  '=': '&#x3D;'
};
```
